# Generated by Engr. Ahsan Mehmood
# Thank me via ahsan.mehmood@outlook.com

# ----------------------------------------------------------------------------
# User LEDs
# ---------------------------------------------------------------------------- 
#set_property IOSTANDARD LVCMOS33 [get_ports G_LED]
#set_property IOSTANDARD LVCMOS33 [get_ports R_LED]
#set_property PACKAGE_PIN W13 [get_ports {G_LED}];  # "GREEN_LED"    # OUTPUT
#set_property PACKAGE_PIN W14 [get_ports {R_LED}];  # "RED_LED"      # OUTPUT


# ----------------------------------------------------------------------------
# User Push Switches
# ---------------------------------------------------------------------------- 
#set_property IOSTANDARD LVCMOS33 [get_ports S2]
#set_property IOSTANDARD LVCMOS33 [get_ports S3]
#set_property PACKAGE_PIN A17 [get_ports {S2}];  # "S2"    # INPUT
#set_property PACKAGE_PIN A14 [get_ports {S3}];  # "S3"    # INPUT

# ----------------------------------------------------------------------------
# Serial Debugger
# ---------------------------------------------------------------------------- 
#set_property IOSTANDARD LVCMOS33 [get_ports SER_TX]
#set_property IOSTANDARD LVCMOS33 [get_ports SER_RX]
#set_property PACKAGE_PIN A16 [get_ports {SER_TX}];  # "SER_TX"    # OUTPUT
#set_property PACKAGE_PIN F15 [get_ports {SER_RX}];  # "SER_RX"    # INPUT

# ----------------------------------------------------------------------------
# BOOT MODE DETECTION
# ---------------------------------------------------------------------------- 
#set_property IOSTANDARD LVCMOS33 [get_ports BOOT_IO_0]
#set_property IOSTANDARD LVCMOS33 [get_ports BOOT_IO_2]
#   JTAG-00,    NAND-01,    SD-11    
#set_property PACKAGE_PIN A6 [get_ports {BOOT_IO_0}];  # "BOOT_IO_0"    # INPUT
#set_property PACKAGE_PIN B7 [get_ports {BOOT_IO_2}];  # "BOOT_IO_2"    # INPUT


# ----------------------------------------------------------------------------
# DATA1 GPIOs - Bank XX
# ---------------------------------------------------------------------------- 
#set_property IOSTANDARD LVCMOS33 [get_ports DATA1[0]]
#set_property IOSTANDARD LVCMOS33 [get_ports DATA1[1]]
#set_property IOSTANDARD LVCMOS33 [get_ports DATA1[2]]
#set_property IOSTANDARD LVCMOS33 [get_ports DATA1[3]]
#set_property IOSTANDARD LVCMOS33 [get_ports DATA1[4]]
#set_property IOSTANDARD LVCMOS33 [get_ports DATA1[5]]
#set_property IOSTANDARD LVCMOS33 [get_ports DATA1[6]]
#set_property IOSTANDARD LVCMOS33 [get_ports DATA1[7]]
#set_property IOSTANDARD LVCMOS33 [get_ports DATA1[8]]
#set_property IOSTANDARD LVCMOS33 [get_ports DATA1[9]]
#set_property IOSTANDARD LVCMOS33 [get_ports DATA1[10]]
#set_property IOSTANDARD LVCMOS33 [get_ports DATA1[11]]
#set_property IOSTANDARD LVCMOS33 [get_ports DATA1[12]]
#set_property IOSTANDARD LVCMOS33 [get_ports DATA1[13]]
# pin#1,2 are 12VDC input and 3,4 are GND
#set_property PACKAGE_PIN A20 [get_ports {DATA1[0]}];  # "DATA1[0]" pin#1-5
#set_property PACKAGE_PIN H16 [get_ports {DATA1[1]}];  # "DATA1[1]" pin#1-6
#set_property PACKAGE_PIN B19 [get_ports {DATA1[2]}];  # "DATA1[2]" pin#1-7
#set_property PACKAGE_PIN B20 [get_ports {DATA1[3]}];  # "DATA1[3]" pin#1-8
#set_property PACKAGE_PIN C20 [get_ports {DATA1[4]}];  # "DATA1[4]" pin#1-9
# pin#1-10  is NC
#set_property PACKAGE_PIN H17 [get_ports {DATA1[5]}];  # "DATA1[5]" pin#1-11
# pin#1-12  is GND
#set_property PACKAGE_PIN D20 [get_ports {DATA1[6]}];  # "DATA1[6]" pin#1-13
#set_property PACKAGE_PIN D18 [get_ports {DATA1[7]}];  # "DATA1[7]" pin#1-14
#set_property PACKAGE_PIN H18 [get_ports {DATA1[8]}];  # "DATA1[8]" pin#1-15
#set_property PACKAGE_PIN D19 [get_ports {DATA1[9]}];  # "DATA1[9]" pin#1-16
#set_property PACKAGE_PIN F20 [get_ports {DATA1[10]}];  # "DATA1[10]" pin#1-17
#set_property PACKAGE_PIN E19 [get_ports {DATA1[11]}];  # "DATA1[11]" pin#1-18
#set_property PACKAGE_PIN F19 [get_ports {DATA1[12]}];  # "DATA1[12]" pin#1-19
#set_property PACKAGE_PIN K17 [get_ports {DATA1[13]}];  # "DATA1[13]" pin#1-20


# ----------------------------------------------------------------------------
# DATA2 GPIOs - Bank XX
# ---------------------------------------------------------------------------- 
#set_property IOSTANDARD LVCMOS33 [get_ports DATA2[0]]
#set_property IOSTANDARD LVCMOS33 [get_ports DATA2[1]]
#set_property IOSTANDARD LVCMOS33 [get_ports DATA2[2]]
#set_property IOSTANDARD LVCMOS33 [get_ports DATA2[3]]
#set_property IOSTANDARD LVCMOS33 [get_ports DATA2[4]]
#set_property IOSTANDARD LVCMOS33 [get_ports DATA2[5]]
#set_property IOSTANDARD LVCMOS33 [get_ports DATA2[6]]
#set_property IOSTANDARD LVCMOS33 [get_ports DATA2[7]]
#set_property IOSTANDARD LVCMOS33 [get_ports DATA2[8]]
#set_property IOSTANDARD LVCMOS33 [get_ports DATA2[9]]
#set_property IOSTANDARD LVCMOS33 [get_ports DATA2[10]]
#set_property IOSTANDARD LVCMOS33 [get_ports DATA2[11]]
#set_property IOSTANDARD LVCMOS33 [get_ports DATA2[12]]
#set_property IOSTANDARD LVCMOS33 [get_ports DATA2[13]]
# pin#1,2 are 12VDC input and 3,4 are GND
#set_property PACKAGE_PIN G20 [get_ports {DATA2[0]}];  # "DATA2[0]" pin#2-5
#set_property PACKAGE_PIN J18 [get_ports {DATA2[1]}];  # "DATA2[1]" pin#2-6
#set_property PACKAGE_PIN G19 [get_ports {DATA2[2]}];  # "DATA2[2]" pin#2-7
#set_property PACKAGE_PIN H20 [get_ports {DATA2[3]}];  # "DATA2[3]" pin#2-8
#set_property PACKAGE_PIN J19 [get_ports {DATA2[4]}];  # "DATA2[4]" pin#2-9
# pin#2-10  is NC
#set_property PACKAGE_PIN K18 [get_ports {DATA2[5]}];  # "DATA2[5]" pin#2-11
# pin#2-12  is GND
#set_property PACKAGE_PIN K19 [get_ports {DATA2[6]}];  # "DATA2[6]" pin#2-13
#set_property PACKAGE_PIN J20 [get_ports {DATA2[7]}];  # "DATA2[7]" pin#2-14
#set_property PACKAGE_PIN L16 [get_ports {DATA2[8]}];  # "DATA2[8]" pin#2-15
#set_property PACKAGE_PIN L19 [get_ports {DATA2[9]}];  # "DATA2[9]" pin#2-16
#set_property PACKAGE_PIN M18 [get_ports {DATA2[10]}];  # "DATA2[10]" pin#2-17
#set_property PACKAGE_PIN L20 [get_ports {DATA2[11]}];  # "DATA2[11]" pin#2-18
#set_property PACKAGE_PIN M20 [get_ports {DATA2[12]}];  # "DATA2[12]" pin#2-19
#set_property PACKAGE_PIN L17 [get_ports {DATA2[13]}];  # "DATA2[13]" pin#2-20


# ----------------------------------------------------------------------------
# DATA3 GPIOs - Bank XX
# ---------------------------------------------------------------------------- 
#set_property IOSTANDARD LVCMOS33 [get_ports DATA3[0]]
#set_property IOSTANDARD LVCMOS33 [get_ports DATA3[1]]
#set_property IOSTANDARD LVCMOS33 [get_ports DATA3[2]]
#set_property IOSTANDARD LVCMOS33 [get_ports DATA3[3]]
#set_property IOSTANDARD LVCMOS33 [get_ports DATA3[4]]
#set_property IOSTANDARD LVCMOS33 [get_ports DATA3[5]]
#set_property IOSTANDARD LVCMOS33 [get_ports DATA3[6]]
#set_property IOSTANDARD LVCMOS33 [get_ports DATA3[7]]
#set_property IOSTANDARD LVCMOS33 [get_ports DATA3[8]]
#set_property IOSTANDARD LVCMOS33 [get_ports DATA3[9]]
#set_property IOSTANDARD LVCMOS33 [get_ports DATA3[10]]
#set_property IOSTANDARD LVCMOS33 [get_ports DATA3[11]]
#set_property IOSTANDARD LVCMOS33 [get_ports DATA3[12]]
#set_property IOSTANDARD LVCMOS33 [get_ports DATA3[13]]
# pin#1,2 are 12VDC input and 3,4 are GND
#set_property PACKAGE_PIN M19 [get_ports {DATA3[0]}];  # "DATA3[0]" pin#3-5
#set_property PACKAGE_PIN N20 [get_ports {DATA3[1]}];  # "DATA3[1]" pin#3-6
#set_property PACKAGE_PIN P18 [get_ports {DATA3[2]}];  # "DATA3[2]" pin#3-7
#set_property PACKAGE_PIN M17 [get_ports {DATA3[3]}];  # "DATA3[3]" pin#3-8
#set_property PACKAGE_PIN N17 [get_ports {DATA3[4]}];  # "DATA3[4]" pin#3-9
# pin#3-10  is NC
#set_property PACKAGE_PIN P20 [get_ports {DATA3[5]}];  # "DATA3[5]" pin#3-11
# pin#3-12  is GND
#set_property PACKAGE_PIN R18 [get_ports {DATA3[6]}];  # "DATA3[6]" pin#3-13
#set_property PACKAGE_PIN R19 [get_ports {DATA3[7]}];  # "DATA3[7]" pin#3-14
#set_property PACKAGE_PIN P19 [get_ports {DATA3[8]}];  # "DATA3[8]" pin#3-15
#set_property PACKAGE_PIN T20 [get_ports {DATA3[9]}];  # "DATA3[9]" pin#3-16
#set_property PACKAGE_PIN U20 [get_ports {DATA3[10]}];  # "DATA3[10]" pin#3-17
#set_property PACKAGE_PIN T19 [get_ports {DATA3[11]}];  # "DATA3[11]" pin#3-18
#set_property PACKAGE_PIN V20 [get_ports {DATA3[12]}];  # "DATA3[12]" pin#3-19
#set_property PACKAGE_PIN U19 [get_ports {DATA3[13]}];  # "DATA3[13]" pin#3-20




# ----------------------------------------------------------------------------
# SD Card - Bank XX
# ---------------------------------------------------------------------------- 
#set_property IOSTANDARD LVCMOS33 [get_ports SD_DAT2]
#set_property IOSTANDARD LVCMOS33 [get_ports SD_DAT3CD]
#set_property IOSTANDARD LVCMOS33 [get_ports SD_CMD]
#set_property IOSTANDARD LVCMOS33 [get_ports SD_CLK]
#set_property IOSTANDARD LVCMOS33 [get_ports SD_DAT0]
#set_property IOSTANDARD LVCMOS33 [get_ports SD_DAT1]
#set_property IOSTANDARD LVCMOS33 [get_ports SD_DETECT]
#set_property PACKAGE_PIN F13 [get_ports {SD_DAT2}];  # DAT2
#set_property PACKAGE_PIN B15 [get_ports {SD_DAT3CD}];  # DAT3/CD
#set_property PACKAGE_PIN C17 [get_ports {SD_CMD}];  # CMD
#set_property PACKAGE_PIN D14 [get_ports {SD_CLK}];  # CLK
#set_property PACKAGE_PIN E12 [get_ports {SD_DAT0}];  # DAT0
#set_property PACKAGE_PIN A9 [get_ports {SD_DAT1}];  # DAT1
#set_property PACKAGE_PIN A12 [get_ports {SD_DETECT}];  # DETECT


# ----------------------------------------------------------------------------
# OPTO-Couplers - Bank XX
# ---------------------------------------------------------------------------- 
#set_property IOSTANDARD LVCMOS33 [get_ports OP_J3P3_SPEED]
#set_property IOSTANDARD LVCMOS33 [get_ports OP_J3P4_PWM]
#set_property IOSTANDARD LVCMOS33 [get_ports OP_J5P3_SPEED]
#set_property IOSTANDARD LVCMOS33 [get_ports OP_J5P4_PWM]
#set_property PACKAGE_PIN V13 [get_ports {OP_J3P3_SPEED}];  # Pin# J3-3  output, active logic low
#set_property PACKAGE_PIN U12 [get_ports {OP_J3P4_PWM}];  # Pin# J3-4  input, active logic low
#set_property PACKAGE_PIN V12 [get_ports {OP_J5P3_SPEED}];  # Pin# J5-3  output, active logic low
#set_property PACKAGE_PIN V15 [get_ports {OP_J5P4_PWM}];  # Pin# J5-4 input, active logic low


# ----------------------------------------------------------------------------
# Clock Sources - Bank XX
# ---------------------------------------------------------------------------- 
#set_property IOSTANDARD LVCMOS33 [get_ports CLK_PS]
#set_property IOSTANDARD LVCMOS33 [get_ports CLK_X5]
#set_property PACKAGE_PIN E7 [get_ports {CLK_PS}];   # input clk 33.333MHz "PS_CLK_500" Clk shared with FLASH memory
#set_property PACKAGE_PIN N18 [get_ports {CLK_X5}];  # input clk 50.000MHz # Use if you have X5 Oscillator and R1372 Resistor are soldered on board
#create_clock -add -name clk_pin -period 10.00 -waveform {0 5} [get_ports { CLK_X5 }];


# ----------------------------------------------------------------------------
# Clock for Ethernet Transceiver
# ---------------------------------------------------------------------------- 
#set_property IOSTANDARD LVCMOS33 [get_ports FCLK_CLK3_0]
#set_property PACKAGE_PIN U18 [get_ports FCLK_CLK3_0]   # if onboard oscillator is not connected

# ----------------------------------------------------------------------------
# Ethernet Transceiver
# ---------------------------------------------------------------------------- 
#set_property IOSTANDARD LVCMOS33 [get_ports GMII_ETHERNET_0_0_rx_clk]
#set_property IOSTANDARD LVCMOS33 [get_ports GMII_ETHERNET_0_0_tx_clk]
#set_property PACKAGE_PIN U14 [get_ports GMII_ETHERNET_0_0_rx_clk]
#set_property PACKAGE_PIN U15 [get_ports GMII_ETHERNET_0_0_tx_clk]

#set_property IOSTANDARD LVCMOS33 [get_ports {GMII_ETHERNET_0_0_rxd[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {GMII_ETHERNET_0_0_rxd[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {GMII_ETHERNET_0_0_rxd[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {GMII_ETHERNET_0_0_rxd[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {GMII_ETHERNET_0_0_tx_en[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {GMII_ETHERNET_0_0_txd[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {GMII_ETHERNET_0_0_txd[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {GMII_ETHERNET_0_0_txd[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {GMII_ETHERNET_0_0_txd[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports GMII_ETHERNET_0_0_rx_dv]
#set_property IOSTANDARD LVCMOS33 [get_ports MDIO_ETHERNET_0_0_mdc]
#set_property IOSTANDARD LVCMOS33 [get_ports MDIO_ETHERNET_0_0_mdio_io]
#set_property PACKAGE_PIN Y17 [get_ports {GMII_ETHERNET_0_0_rxd[3]}]
#set_property PACKAGE_PIN V17 [get_ports {GMII_ETHERNET_0_0_rxd[2]}]
#set_property PACKAGE_PIN V16 [get_ports {GMII_ETHERNET_0_0_rxd[1]}]
#set_property PACKAGE_PIN Y16 [get_ports {GMII_ETHERNET_0_0_rxd[0]}]
#set_property PACKAGE_PIN W19 [get_ports {GMII_ETHERNET_0_0_tx_en[0]}]
#set_property PACKAGE_PIN W18 [get_ports {GMII_ETHERNET_0_0_txd[0]}]
#set_property PACKAGE_PIN Y18 [get_ports {GMII_ETHERNET_0_0_txd[1]}]
#set_property PACKAGE_PIN V18 [get_ports {GMII_ETHERNET_0_0_txd[2]}]
#set_property PACKAGE_PIN Y19 [get_ports {GMII_ETHERNET_0_0_txd[3]}]
#set_property PACKAGE_PIN W15 [get_ports MDIO_ETHERNET_0_0_mdc]
#set_property PACKAGE_PIN Y14 [get_ports MDIO_ETHERNET_0_0_mdio_io]
#set_property PACKAGE_PIN W16 [get_ports GMII_ETHERNET_0_0_rx_dv]














